### ISSUE TITLE
update to yui compressor 2.4.6 to resolve some bugs while compressing

### ISSUE THREAD

**Issue by geertbrit** [dirkmc/press#13]
Yahoo recently released a new version of yui compression: 2.4.6. 

This solves a couple of bugs. The ones I encountered: 
- http://yuilibrary.com/projects/yuicompressor/ticket/2528022
- http://www.456bereastreet.com/archive/201012/yui_compressor_and_css_media_queries/

I quickly did a drop-in replacement of 2.4.2 to 2.4.6 in the press-module map and all seems to work well. 

Thanks. 
Geert-Jan

**Comment by dirkmc** [comment]
Thanks for the bug report, I'll update it as soon as possible

**Comment by dirkmc** [comment]
Updated. Thanks!

**Comment by geertbrit** [comment]
Thanks back at you :-)

2011/6/23 dirkmc <
reply@reply.github.com>
