### ISSUE TITLE
Be great to have namespaces for groups of files

### ISSUE THREAD

**Issue by dabeeeenster** [dirkmc/press#2]
Hi,

When my visitors hit my homepage they only need a subset of the css and javascript served to them - the rest can be served if they log into the application. 

It would be great if you could say something like:
# {press.script 'mootools-1.2.4.js'  id='homepage'/}
# {press.script 'mootools-1.2.4.4-more.js' id='homepage' /}
# {press.compressed-script id='homepage'/}

and then once logged in include another set of directives with a different ID.

**Comment by dirkmc** [comment]
press is designed to be transparent to the application developer, meaning that you use #{press.script} in the same way as you'd use #{script}. So for example:
#{if loggedIn}
  #{press.script 'optionalScript.js'}
#{/if}

If you'd like to try a module that's designed along the lines you're suggesting, you might want to check out the greenscript plugin, which I think does something similar:
http://www.playframework.org/modules/greenscript

Also if possible you should use a CDN for a library like mootools, it'll likely be faster than your own server. Even if there isn't a CDN, it's probably best to use the minimized version.
