### ISSUE TITLE
press overriding flash scope

### ISSUE THREAD

**Issue by sauravshah** [dirkmc/press#21]
Take the secure module for example.
1. Add a controller annotated with @With(Secure.class)
2. Override the secure login template.
3. Use press to serve the css and javascript

If you go to http://yourhost:port/controller-path you should see a login page. After logging in the page will take you to http://yourhost:port/ instead of http://yourhost:port/controller-path. The secure module stores the continue url in the flash cookie which is deleted by the press request. 
A flash.keep()  while serving press files would probably solve this issue.

**Comment by dirkmc** [comment]
I wasn't able to recreate the exact issue you described, but I've added a fix that I think should solve it. Please try out the latest version of the plugin and close this issue if it works.
Thanks,
Dirk

**Comment by sauravshah** [comment]
Awesome! Works now.

**Comment by dirkmc** [comment]
Great, thanks for the bug report.
