### ISSUE TITLE
PressException

### ISSUE THREAD

**Issue by dabeeeenster** [dirkmc/press#3]
Getting this on some, but not all, pages in my app. Can't quite figure out what it is in the page that is causing this.

@645d5k7kc
Internal Server Error (500) for request GET /coach/clients

Oops: PressException
An unexpected error occured caused by exception PressException: Number of file compress requests found in response (0) not equal to number of files added to compression (10). Please report a bug.

play.exceptions.UnexpectedException: Unexpected Error
    at play.Invoker$Invocation.onException(Invoker.java:153)
    at play.Invoker$Invocation.run(Invoker.java:195)
    at Invocation.HTTP Request(Play!)
Caused by: press.PressException: Number of file compress requests found in response (0) not equal to number of files added to compression (10). Please report a bug.
    at press.Compressor.getFileListOrder(Compressor.java:224)
    at press.Compressor.saveFileList(Compressor.java:201)
    at press.Plugin.afterActionInvocation(Plugin.java:105)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:305)
    ... 1 more

**Comment by dirkmc** [comment]
Hmmm... that can happen if there's an exception thown from your template, after some #{press} tags have been executed but before template execution finished. Are you using the latest version of press? It has a more informative error message for that particular case.

**Comment by dabeeeenster** [comment]
If I disable the press module the template works fine - there are no errors in the logs. I'm using 1.0.9...This are only on a few of my page templates but most of them work fine. The press tags are being used in include files if that helps?

**Comment by dirkmc** [comment]
1.0.9 is the latest version. I'll explain a bit more what's happening so it might give us a clue..
1. Each time you use the #{press.script} tag it outputs a bit of code that adds the file to a list.
2. When rendering is complete and the response is ready to be sent to the browser, press scans through the response to determine the order in which the <script> tags are output. This is necessary because the order in which templates are called is not necessarily the same as the order in which <script> tags are output.

In this case it seems like the #{script} tag is being included 10 times, but in the response it can't find any of the corresponding <script> tags.

Does this happen every time? If so, could you please paste the contents of the template file that's causing the problem.

Thanks for taking the time to help out :)

**Comment by dirkmc** [comment]
I just re-read your previous message... when you say the press tags are being used in include files, do you mean that they're in a template that has been called using the #{include} tag?

**Comment by dabeeeenster** [comment]
Yes the decorator tempate {include}'s header.html and footer.html

**Comment by dirkmc** [comment]
Ok thanks, a couple more questions:
Is the problem only occurring when you include those two files?
Does it occur every time you include them?
Could you copy the code where you call the #{press.script} tags.
Thanks again

**Comment by dabeeeenster** [comment]
Lots of pages use this decorator and the two includes - it's only a couple of pages that through the error. Everytime I hit these two pages I see the error. The decorator is (abbreviated)

```
#{include '/include/header.html' /}
<ul class="nonPublicTabs clearfix" id="nonPublicTabs">
<div id="outer">
<div id="content">
    <div id="main" class="clearfix">
        #{doLayout /}
    #{include '/include/footer.html' /}
```

And then header:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>JigsawBox &bull; #{get 'title' /}</title>
<link rel="shortcut icon" href="/public/images/favicon.ico" type="image/x-icon" />
#{press.stylesheet 'reset.css' /}
#{press.stylesheet 'base.css' /}
#{press.stylesheet 'mif-tree.css' /}
#{press.stylesheet 'mediaboxAdvWhite.css' /}
#{press.compressed-stylesheet /}
#{if cssPath != null}
<link rel="stylesheet" href="/stylesheets/${cssPath}"/>
#{/if}
```

footer

```
#{press.script 'mootools-1.2.4.js' /}
#{press.script 'mootools-1.2.4.4-more.js' /}
#{press.script 'mooRainbow.1.2b2.js' /}
#{press.script 'tabs.js' /}
#{press.script 'utils.js' /}
#{press.script 'autoRotatingTabs.js' /}
#{press.script 'mif.tree-v1.2.6.js' /}
#{press.script 'ssg-mif.tree.js' /}
#{press.script 'mediaboxAdv-1.2.0.js' /}
#{press.script 'init.js' /}
#{press.compressed-script /}

#{if !site.equals('public')}
<script type="text/javascript" src="/public/ckeditor/ckeditor.js"></script>
#{/if}

#{if customJS != null}
<script type="text/javascript" src="/public/javascripts/custom/${customJS}"></script>
#{/if}
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-15428338-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
```

**Comment by dabeeeenster** [comment]
Right - my apologies. We're actually gzipping the templates causing issues before sending them, which I guess will be causing the issue. Maybe we'll move the GZip out to Apache. Apologies for the incorrect bug report.

**Comment by dirkmc** [comment]
Ah ok that's likely to be what's causing the problem - in that case when press scans the response it won't find the placeholder tags. How are you gzipping the pages? I'd like to add something to the gotchas section.

**Comment by dabeeeenster** [comment]
We rolled our own code to do the gzip - I guess the plugin picks up the response after they have been applied...

**Comment by dirkmc** [comment]
Ok cheers for letting me know
