### ISSUE TITLE
Bug in outputDir directive

### ISSUE THREAD

**Issue by javialeon** [dirkmc/press#32]
I'm using press module 1.0.33 and is ignoring the outputDir directive in both cases, js and css. If I set it or not, is always the same, the compressed files are been created in my project root directory. I have this in my application.conf file:

press.enabled=true
press.cache=Change
press.cache.clearEnabled=false
press.inMemoryStorage=false
press.js.sourceDir=/public/javascripts/
press.css.sourceDir=/public/stylesheets/
press.js.outputDir=/public/compressed/
press.css.outputDir=/public/compressed/

And my file structure is this:

/my_project
    /app
    /public
        /images
        /javascripts
        /stylesheets
    *-compressed.css
    *-compressed.js

I tried to previously create this directory or even the javascripts/press and stylesheets/press directories with no change.

The plugin isn't giving me any Exception, just saving the file in my project root.

I'm developing in OSX and my production server is Centos and in both environments the result is the same.

Is anything wrong with my configuration? Did I forget something?

Thank for time and effort cause this is a great Play! module.

**Comment by dirkmc** [comment]
Thanks for the bug report, I'll take a look at it

**Comment by dirkmc** [comment]
This bug should now be fixed. Please try the latest version of the plugin: 1.0.35
Thanks for your help
Dirk
