### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by jvosloo** [dirkmc/press#34]
Hi Dirk

Firstly -  thanks again for this excellent module. It's one of the few that we really could not live without.

I'm using the latest version of the module (1.0.36) and it seems that on line 84 of the PressWriter class, you create a new BufferedReader, but then never call .close() on it?

Perhaps adding a  finally block will sort it out, something like this:

finally {
 if (reader != null) {
   try {
     reader.close();
   } catch (Exception e) {
     // Log warning if necessary
   }
 }

**Comment by dirkmc** [comment]
Hey Johan,
Nice catch!
Could you submit a pull request?
Thanks,
Dirk

**Comment by jvosloo** [comment]
That's my 1st Github pull request - hope it's ok :)
Please let me know if I didn't do it correctly.

**Comment by dirkmc** [comment]
Looks good, thanks again

**Comment by dirkmc** [comment]
I simplified the exception handling a little bit so it's 99% likely to close the stream instead of 100%, just makes the code a bit cleaner. Thanks for the patch!

**Comment by jvosloo** [comment]
Ha!  I didn't like the code either, but I was too scared to contribute less than bulletproof code :). Glad you cleaned it up.
Johan Vosloo
M: 081 519 9301

-----Original Message-----

**Comment by dirkmc** [comment]
:)
