### ISSUE TITLE
Invalid <link> tag being created

### ISSUE THREAD

**Issue by nzakas** [dirkmc/press#6]
When outputting the compressed-stylesheet, the format is:

<link ...></link>

The closing </link> tag is incorrect, as <link> doesn't require a closing tag like <script> does. The </link> tag should be omitted.

**Comment by dirkmc** [comment]
Hi, sorry for the late response, Im currently on holidays.
I think that all tags must be closed in order to be valid xhtml:
http://www.w3schools.com/XHTML/xhtml_html.asp

**Comment by nzakas** [comment]
Yes, this is true for XHTML, but not for HTML. For XHTML, it's more appropriate to use the following syntax:

<link rel="stylesheet" type="text/css" href="foo.css" />

But in HTML, this is (along with the current code) is invalid. The correct format for HTML is:

<link rel="stylesheet" type="text/css" href="foo.css">

If you're concerned about XHTML-compatibility, can you add an option for HTML vs. XHTML mode?

**Comment by dirkmc** [comment]
I´m not sure there´s a use case for producing HTML that is not XHTML compliant... why would you want to do that?

**Comment by nzakas** [comment]
From your comment, it seems like you believe people primarily write XHTML now? If so, let me assure you that this is not true. I work at Yahoo, and all sites are written in HTML, not XHTML. Google also uses just HTML. 

There are a lot of people who still write just HTML, so adding this configuration option would allow you to support the largest number of developers possible.

**Comment by dirkmc** [comment]
I think maybe you're talking about html5? xhtml has been around since 2000. html5/xhtml5 are newer standards and are not yet completely supported in the major browsers. Anyway, closing tags is standard, and is supported by all major browsers. Not closing tags is no longer standard and may not always be supported by the browsers. Therefore I'm going to leave it as it is and close this thread. Thanks for your comments.

**Comment by nzakas** [comment]
Actually, I'm talking about HTML 4, which is the predecessor to both XHTML and HTML5. Contrary to popular belief, XHTML did not replace HTML 4, and in fact, there is a very large portion of the web development community still writing to HTML 4 (with the intent of transitioning to HTML5). You can easily support these additional developers by adding a configuration to omit the closing tag if the page isn't using XHTML. I'd even be happy to code it up and send you the diffs.

I think this is a really useful plugin, and I'd just like to ensure that the largest number of developers can make use of it.

**Comment by dalizard** [comment]
@mockduck There's no such thing as XHTML5. Not closing tags IS standard. You are all wrong here.

**Comment by rgrove** [comment]
mockduck, HTML5 explicitly does _not_ require end tags for many elements, just like HTML4. The XHTML syntax is supported in HTML5, but is not required. Most developers implementing new HTML5 markup these days do not use the XHTML syntax.

See http://www.whatwg.org/specs/web-apps/current-work/multipage/syntax.html#elements-0

**Comment by mathiasbynens** [comment]
@dalizard XHTML5 is the XML serialization of HTML5. [It does exist](http://mathiasbynens.be/notes/xhtml5), but there’s no point in using it over “regular” HTML5 (unless you’re a sadistic bastard who likes to write code like `<img src="foo"></img>`).

+1 to adding an option to omit the closing tag (and making it the default).

**Comment by clintandrewhall** [comment]
Good lord, this is giving me a headache.  I still don't understand the double-negative here.

"Not closing tags is no longer standard"

Look, it's really simple: if you're writing HTML (in ANY version) closing tags is not _required_ but it _is encouraged_.  It's easier to read, easier for browsers (and people like me) to parse.  Browsers simply have to be forgiving of poor syntax from poor developers.

XHTML requires closing tags to be meet the X(ML) requirement.

I've never heard of an argument to _not_ close tags.  Required or not, it's just good practice.

**Comment by rgrove** [comment]
clintandrewhall: Do you advocate `<img src="foo.png"></img>` then? Because that's essentially what's happening here, but with `<link>`.

**Comment by mathiasbynens** [comment]
@clintandrewhall:

> I've never heard of an argument to not close tags.

HTML does not allow a closing `</link>` tag. How’s that for an argument?

**Comment by clintandrewhall** [comment]
In point of fact, both &lt;link&gt; and &lt;img&gt; shouldn't be closed as:

&lt;tag&gt;&lt;/tag&gt;

they should be closed as 

&lt;tag /&gt;

THAT is how a tag without children _should_ be "closed".

**Comment by mathiasbynens** [comment]
> THAT is how a tag without children should be closed.

You mean a tag without _content_.

Anyway, that may be _your_ opinion, and I can see the argumentation behind it, but at the end of the day **the HTML5 spec** allows you to choose whether to use the XML solidus or not. So it’s up to personal preference.

However, in this case, it’s about `<link rel="stylesheet" href="foo"></link>`, which doesn’t conform to any HTML spec (even though it’s valid XHTML5). That’s not a matter of preference, it’s a simple fact.

**Comment by jalbertbowden** [comment]
@mathiasbynens the only argument i've heard of for not closing them is because its less code. and i cringed, but ok, sure if that's really why he was doing it. but just think of how massive and/or the other constraints a page/site would be facing if it were literally resorting to not close them to save chars.

**Comment by dirkmc** [comment]
My apologies, you´re correct that the HTML spec specifically requires there to be no closing link tag. I had always thought it was optional in HTML, and required in XHTML. It seems that the only sensible option is to provide a configuration option as you suggested. I´m currently on holidays, so I´ll do it next week when I´m back in Buenos Aires.
Thanks all for your comments.

PS github sure makes it hard to write things about HTML tags :)

**Comment by nzakas** [comment]
Cool, thanks!

**Comment by mathiasbynens** [comment]
@mockduck (and @nzakas):

> PS github sure makes it hard to write things about HTML tags :)

Just wrap your code in backticks (`) and it will show up just fine. Read more here: http://github.github.com/github-flavored-markdown/

**Comment by jalbertbowden** [comment]
hey guys, with all due respect, the first response includes a W3Schools reference === automatic default in the debate. i am applying this strategy to everything now, i am wasting entirely too much time and energy going back and forth with pro W3Schoolers. i can handle being wrong, being called out, whatever....as long as its a proactive reason. the overwhelming stereotype of the pro w3schoolers is that they are not as up to date aka on the bleeding edge. and thats fine, just not what i am searching for in my dev life. 
sorry for the rant, and apologies if you take offense to this. it's not an attack on you, it's an attack on w3schools, bad information, and keeping webdev/webcomm pushing full steam ahead towards Standards. 
cheers.

**Comment by dirkmc** [comment]
A new version of press is now available with an option to make the output HTML compatible. By default output is XHTML compatible. This is so that by default press will behave the same way as play's stylesheet tag:
https://github.com/playframework/play/blob/master/framework/templates/tags/stylesheet.tag
You may want to raise the issue in the play group?

Thanks again for your bug report and comments.

**Comment by dirkmc** [comment]
To make output html compatibile:
press.htmlCompatible=true
