### ISSUE TITLE
Compatibility with the Scala module

### ISSUE THREAD

**Issue by jareware** [dirkmc/press#8]
The plugin (1.0.12) doesn't seem to be compatible with the latest Scala module (0.8).  After enabling both modules, restarting and refreshing, I get:

```
Compilation error

The file {module:press-1.0.12}/app/press/PressFileFilter.java could not be compiled. Error raised is : illegal start of type declaration

In {module:press-1.0.12}/app/press/PressFileFilter.java (around line 22)
```

Ideas..?

**Comment by jareware** [comment]
Actually, just removing the trailing semicolon from app/press/PressFileFilter.java seems to fix the issue.

**Comment by dirkmc** [comment]
Interesting. Thanks for discovering that! I'm going to remove the trailing semi-colon and report a bug in the play group.

**Comment by dirkmc** [comment]
I've also uploaded a new version of press, 1.0.14
Thanks again

**Comment by jareware** [comment]
np, keep up the good work!
